# Generated by Django 4.0.1 on 2022-01-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savage_bcw', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
