# Generated by Django 4.0.1 on 2022-01-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savage_bcw', '0002_rename_games_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='member',
            new_name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='games',
            field=models.ManyToManyField(to='savage_bcw.Game'),
        ),
    ]
