# Generated by Django 4.0.1 on 2022-01-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savage_bcw', '0004_remove_member_games_alter_game_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='games',
            field=models.ManyToManyField(related_name='members', to='savage_bcw.Game'),
        ),
    ]
