# Generated by Django 4.0.1 on 2022-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savage_bcw', '0005_remove_game_members_member_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='games',
            field=models.ManyToManyField(related_name='member', to='savage_bcw.Game'),
        ),
    ]
